import { Inter } from 'next/font/google'
import './globals.css'



export const metadata = {
  title: 'Diogo dos Pano',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}
